export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOADING_LOGIN = 'LOADING_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const LOADING_REGISTER = 'LOADING_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';
export const NO_TOKEN = 'NO_TOKEN';
export const GET_USER = 'GET_USER';


export const LOADING_SPECIALITIES = 'LOADING_SPECIALITIES';
export const GET_SPECIALITIES = 'GET_SPECIALITIES';

export const LOADING_DOCTORS = 'LOADING_DOCTORS';
export const GET_DOCTORS = 'GET_DOCTORS';

export const LOADING_APPOINTMENTS = 'LOADING_APPOINTMENTS';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';

