

export const SERVER_DOWN = 'SERVER_DOWN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_LOADING = 'REGISTER_LOADING';

export const NO_TOKEN = 'NO_TOKEN';
export const GET_USER = 'GET_USER';


export const LOADING_SPECIALITIES = 'LOADING_SPECIALITIES';
export const GET_SPECIALITIES = 'GET_SPECIALITIES';

export const LOADING_DOCTORS = 'LOADING_DOCTORS';
export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_SPECIALITY_DOCTORS = 'GET_SPECIALITY_DOCTORS';

export const LOADING_APPOINTMENTS = 'LOADING_APPOINTMENTS';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const BOOK_APPOINTMENT = 'BOOK_APPOINTMENT';

export const LOADING_HEALTHINFO = 'LOADING_HEALTHINFO';
export const GET_HEALTHINFO = 'GET_HEALTHINFO';
export const UPDATE_HEALTHINFO = 'UPDATE_HEALTHINFO';
